### ISSUE TITLE
Spike - Server-side testing

### ISSUE THREAD

**Issue by indifferentghost** [100devs/course-tracker#7]
- [x] Research the modern way to do server-side tests

**Comment by TelescopeThieves** [comment]
Recommendation: Jest paired with SuperTest. 

Jest runs parallel test leading to faster execution. 
Is developed by facebook and could be useful for testing the react side. 
Syntax is slightly more digestible to my eye than Mocha & Chai.

**Comment by indifferentghost** [comment]
Closed by comment above
