### ISSUE TITLE
Task - Server Setup

### ISSUE THREAD

**Issue by indifferentghost** [100devs/course-tracker#9]
The following should be done in `packages/server`:

**Install**:
- [ ] mongoose
- [ ] express
- [ ] password hashing - bcrypt
- [ ] sessions

**Setup**:
- [ ] Setup a main server using express
- [ ] Api routes should have a root router of `/api`.
  (for example an authentication route might be `/api/auth/login`)
- [ ] Expect a React App to build into this in production environment. This'll require a snippet similar to `app.use(express.static(path.join(__dirname, 'build')));` gated by environment.

**Comment by indifferentghost** [comment]
Because of the requirement of adding MongoDB, this is blocked by [External Considerations](https://github.com/100devs/course-tracker/projects/1#card-67171805) #8

**Comment by justrubyk** [comment]
Thank you!
